### ISSUE TITLE
Can't edit main post after recent Discourse update (2.7.0.beta6) ?

### ISSUE THREAD

**Issue by alexAubin** [paviliondev/discourse-multilingual#11]
For some reason the recent update in Discourse seems to have broken the post update mecanism but the issue seems to lie our discourse-multilingual plugin

Problematic behavior:
- create a topic with a language tag
- click edit on the first post
- actually edit the topic
- click Save
- popup shows up with "500 Internal Server Error"

I went to our.forum.tld/logs and found the corresponding stacktrace:

```
ArgumentError (wrong number of arguments (given 3, expected 2))
plugins/discourse-multilingual/plugin.rb:359:in `block (2 levels) in activate!'
lib/post_revisor.rb:469:in `block (2 levels) in update_topic'
lib/post_revisor.rb:467:in `each'
lib/post_revisor.rb:467:in `block in update_topic'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
activerecord (6.0.3.5) lib/active_record/transactions.rb:212:in `transaction'
lib/post_revisor.rb:466:in `update_topic'
lib/post_revisor.rb:367:in `revise'
lib/post_revisor.rb:271:in `revise_post'
lib/post_revisor.rb:185:in `block in revise!'
[...]
```

So the issue seems to lie in this piece of code expecting 3 args instead of 2 (but i'm not super familiar with Ruby) : https://github.com/paviliondev/discourse-multilingual/blob/master/plugin.rb#L359

Thank you for your work !

**Comment by alexAubin** [comment]
ˢᵐᵒˡ ᵇᵘᵐᵖ

**Comment by angusmcleod** [comment]
@alexAubin Thanks for reporting this and sorry I've been so slow on this plugin. I've made a number of fixes here, including addressing this. I've also set up a full CI process for this plugin and integrated it into our standard plugin workflow, as clearly it's useful to some. Closing this issue, but if there are any future issues, please feel free to report.
