### ISSUE TITLE
500 error when trying to update language tag of a post created before Multilingual installed/enabled

### ISSUE THREAD

**Issue by sociocracyforall** [paviliondev/discourse-multilingual#12]
When I try to change the language tag of posts which were made before the plugin was enabled, I cannot - I get a 500 error. Whether it’s my own post or someone elses.

On these forums:
https://forums.sociocracyforall.org

reply on Discourse Meta
https://meta.discourse.org/t/multilingual-plugin/142740/42?u=oreillyc

**Comment by sociocracyforall** [comment]
Error Logs say:


763
Job exception: {"error"=>{"code"=>403, "message"=>"Requests from referer <empty> are blocked.", "errors"=>[{"message"=>"Requests from referer <empty> are blocked.", "domain"=>"global", "reason"=>"forb
1:24 pm
12
ArgumentError (wrong number of arguments (given 3, expected 2)) lib/post_revisor.rb:473:in `block (2 levels) in update_topic' lib/post_revisor.rb:471:in `each' lib/post_revisor.rb:471:in `block in upd
1:24 pm
12
Failed to handle exception in exception app middleware : wrong number of arguments (given 3, expected 2)
1:24 pm

**Comment by angusmcleod** [comment]
@sociocracyforall Could you test all your issues again on the latest code and report any further issues, or make any further feature requests over at thepavilion.io? Thanks :)
