### ISSUE TITLE
Missing Language Tag Error Message not very clear to the end user

### ISSUE THREAD

**Issue by sociocracyforall** [paviliondev/discourse-multilingual#13]
I understand what it's telling me as an admin/developer, but all it says is:
translation missing: en.tags.required_tags_from_group

Can this be improved?
I'm wondering... perhaps I could contribute to the translation somewhere?

Discourse Meta reply: https://meta.discourse.org/t/multilingual-plugin/142740/42?u=oreillyc

**Comment by sociocracyforall** [comment]
I notice in the Text panel under Customize in the Admin settings I can search for :
tags.required_tags_from_group.one
and
tags.required_tags_from_group.other

But this is different than the error I see. I don't see how I can add a message for a text without the .one and .other part.

**Comment by vccoffey** [comment]
<img width="676" alt="Screen Shot 2021-07-23 at 12 54 58 PM" src="https://user-images.githubusercontent.com/59817868/126834651-a730ab60-b9c7-4afd-a13a-f07ba5d7bcbc.png">
