### ISSUE TITLE
Cannot tag topic with a language

### ISSUE THREAD

**Issue by sylque** [paviliondev/discourse-multilingual#2]
I don't know what I'm doing wrong, but I cannot tag a topic with a language, both when creating a new topic or editing an old one. 

I can choose the language in the language picker:
![image](https://user-images.githubusercontent.com/42490951/75769578-b7257280-5d46-11ea-8f80-8b88450f51da.png)

But it won't be saved in the topic:
-  If "multilingual require content language tag" is not set, everything looks normal, but if I refresh the browser, the topic doesn't have the language tag anymore.
-  If "multilingual require content language tag" is set, I immediately get the following error:
![image](https://user-images.githubusercontent.com/42490951/75769793-09669380-5d47-11ea-8a1e-410ea2365096.png)
```
```

**Comment by angusmcleod** [comment]
Thanks for the report, looks like an issue. I'm trying to repro this. 

Just checking, these are site settings are enabled?

tagging enabled: true
multilingual enabled: true
multilingual content languages enabled: true

And the language you're using as a content language (English) is enabled as a content language in http://localhost:3000/admin/multilingual/languages.

If any of those things are not true, there would still be an issue, but it'll help me narrow it down.

**Comment by sylque** [comment]
Thanks for your answer.

Everything looks ok:
* tagging enabled -> checked
* multilingual enabled -> checked
* multilingual content languages enabled -> checked
* languages -> English and French

I've just updated to your latest version and the issue still occurs.

I forgot to give you the debug console error I also get:
```
PUT http://localhost:3000/t/test-francais-du-plugin-multilingual/17 422 (Unprocessable Entity)
  XMLHttpRequest.send @ includes.js?v=67dd1c2571ced7fc74ae7f1813e47bdf:760
  send @ jquery:9838
  ajax @ jquery:9435
  performAjax @ discourse/lib/ajax:153
  initializePromise @ ember:63131
  Promise @ ember:63653
  ajax @ discourse/lib/ajax:167
  update @ discourse/models/topic:635
  finishedEditingTopic @ discourse/controllers/topic:819
  _join @ ember:56371
  join @ ember:56082
  join @ ember:42874
  eval @ ember:10082
  instrument @ ember:39205
  eval @ ember:10081
  click @ discourse/components/d-button:102
  trigger @ ember:35188
  superWrapper @ ember:32547
  _run @ ember:56389
  _join @ ember:56365
  join @ ember:56082
  join @ ember:42874
  eval @ ember:35289
  instrument @ ember:39205
  handleEvent @ ember:35285
  handleEvent @ ember:34222
  eval @ ember:34612
  dispatch @ jquery:5238
  elemData.handle @ jquery:5045
Uncaught Error: Unprocessable Entity
    at unwrapErrorThrown (ember:27687)
    at errorFor (ember:27668)
    at onerrorDefault (ember:27651)
    at Object.trigger (ember:62805)
    at eval (ember:63664)
    at invoke (ember:55664)
    at Queue.flush (ember:55556)
    at DeferredActionQueues.flush (ember:55760)
    at Backburner._end (ember:56336)
    at Backburner.end (ember:56022)
```

**Comment by sylque** [comment]
Tried a bit of debugging, hope this helps:

I changed [this code](https://github.com/paviliondev/discourse-multilingual/blob/master/plugin.rb#L217) to this one:
```
add_class_method(:discourse_tagging, :validate_require_language_tag) do |guardian, topic, tag_names|
  puts "tag_names: " + tag_names.inspect
  puts "guardian.topic_requires_language_tag: " + guardian.topic_requires_language_tag.inspect
  puts "DiscourseTagging::TAG_GROUP_TAG_IDS_SQL: " + DiscourseTagging::TAG_GROUP_TAG_IDS_SQL
  puts "Multilingual::ContentTag::GROUP: " + Multilingual::ContentTag::GROUP
	
  if (...)
    ...
    false
  else
    true
  end
end
```

And got the following output:
```
tag_names: ["fr"]
guardian.topic_requires_language_tag: true
DiscourseTagging::TAG_GROUP_TAG_IDS_SQL:       SELECT tag_id
        FROM tag_group_memberships tgm
  INNER JOIN tag_groups tg
          ON tgm.tag_group_id = tg.id
Multilingual::ContentTag::GROUP: content_languages
```

**Comment by sylque** [comment]
There's a change with the latest version: I get neither the error modal box, nor the error message in the console anymore. However, the language tag still doesn't hold: when I refresh the browser, the language tag is gone.

**Comment by sylque** [comment]
Also, I think there's a new exception in the console at load time (on any page):
```
GET http://localhost:3000/extra-locales/tags?v=74cc3757df3a7f4c68bfebee2155cd65 net::ERR_ABORTED 403 (Forbidden)
```

**Comment by angusmcleod** [comment]
@sylque This is resolved now. Apologies for such a long delay.
