### ISSUE TITLE
Topic filtering for content languages does not work

### ISSUE THREAD

**Issue by psychedel** [paviliondev/discourse-multilingual#29]
Filtering do nothing currently (or is it only my issue?)
![image](https://user-images.githubusercontent.com/13717891/173241480-285a5eda-f765-4cf4-aac1-ef47006e056a.png)

**Comment by angusmcleod** [comment]
Hey, you'll need to provide more details about what you mean by "doing nothing". From your screenshot I see that one of your content languages is English (US) and that the only topic you're seeing in the list is one tagged with English (US). Depending on what other topics you have on your instance, this could be working as expected. Please read the documentation to understand how it's meant to work: https://thepavilion.io/t/content-languages/2545
