### ISSUE TITLE
Disabling the plugin breaks the Discourse instance

### ISSUE THREAD

**Issue by sylque** [paviliondev/discourse-multilingual#3]
I've just unchecked `multilingual_enabled` and now my Discourse (dev) instance won't work. Here is what is displayed when I try to connect:
![image](https://user-images.githubusercontent.com/42490951/75776284-fe663000-5d53-11ea-8526-b66bc8202cba.png)

**Comment by sylque** [comment]
I could fix my Discourse instance by manually setting `multilingual_enabled` back:
```
cd discourse
bundle exec rails c
SiteSetting.multilingual_enabled = true
```

**Comment by angusmcleod** [comment]
Thanks for this feedback as well. I've pushed some updates that should fix this. Let me know how they go

**Comment by sylque** [comment]
It works now. Thanks a lot.
