### ISSUE TITLE
category translations not working 

### ISSUE THREAD

**Issue by pushpinder6805** [paviliondev/discourse-multilingual#32]

**Comment by merefield** [comment]
This should be fixed in #34

**Comment by merefield** [comment]
This is now merged, tempted to Close, but please let us know if it solves your issue @pushpinder6805

**Comment by pushpinder6805** [comment]
![image](https://user-images.githubusercontent.com/52063297/178149005-7660e2be-01fb-49eb-a750-a60738ff0836.png)

uploaded yml file to change primary name of 2 categories (hr language crotia which is already added )  ,but instead it is showing name change for all sub categories , format for file is shown in above image , please let me know if i structured the yml file wrong

**Comment by merefield** [comment]
Investigating

**Comment by merefield** [comment]
@pushpinder6805 we've just merged a PR that should make them work again, please confirm.

**Comment by merefield** [comment]
I believe this is working now, so will Close this for time being, but free free to comment.
