### ISSUE TITLE
When disabling the plugin, an empty tag group is left behind

### ISSUE THREAD

**Issue by sylque** [paviliondev/discourse-multilingual#4]
This is a only a minor annoyance.

When the plugin is enabled, you get the tag group called "Multilingual content tags":
![image](https://user-images.githubusercontent.com/42490951/75883054-a77b5c00-5e22-11ea-945a-9987dfa6cdd7.png)

When I disable the plugin, the "Multilingual content tags" is replaced by a strange empty group:
![image](https://user-images.githubusercontent.com/42490951/75883158-d560a080-5e22-11ea-8371-06604811dcd1.png)

This "ghost group" might be problematic if a 3rd party plugin parses tag groups and expect them to have a non-empty name (I had to fix one of my plugins for that reason).

**Comment by sylque** [comment]
Maybe there is an incompatibility between plugins here (related to tag groups). 

This might also cause https://github.com/paviliondev/discourse-multilingual/issues/2. 

I will investigate further.

**Comment by sylque** [comment]
Didn't find any interaction with other plugins.

However, there is something more to the current issue: when disabling the plugin, not only is the "Multilingual content tags" group transformed into a ghost group, but all other groups loose their title.

With the plugin enabled:
![image](https://user-images.githubusercontent.com/42490951/75895955-a2280c80-5e36-11ea-9912-6a840c0ed924.png)

With the plugin disabled:
![image](https://user-images.githubusercontent.com/42490951/75896199-fdf29580-5e36-11ea-956b-f4e66632a93b.png)

**Comment by angusmcleod** [comment]
Are you seeing these same issues after the latest updates?

**Comment by sylque** [comment]
No change on my side: issues still occur. Can you reproduce them or is there something different on my side?

**Comment by angusmcleod** [comment]
This issue should also be resolved now.
