### ISSUE TITLE
Discourse instance not working when enabling the plugin

### ISSUE THREAD

**Issue by juandans01** [paviliondev/discourse-multilingual#48]
Hey everyone,
so yesterday updated my discourse instance with the latest version of the plugin doing a ./launcher rebuild app, the update process ends successfully but after that i'm seeing this:

![image](https://user-images.githubusercontent.com/13892005/178785199-71b28ddf-e813-4939-a4d3-4d6ec7522b1a.png)

I checked and removing the plugin from the config file makes everything work

this is the stacktrace of the error, any help is super appreciated
```
NoMethodError (undefined method `to_sym' for nil:NilClass)
(eval):32:in `_fast_attributes'
app/models/site.rb:181:in `json_for'
app/controllers/application_controller.rb:628:in `preload_anonymous_data'
app/controllers/application_controller.rb:435:in `preload_json'
app/controllers/application_controller.rb:415:in `block in with_resolved_locale'
app/controllers/application_controller.rb:415:in `with_resolved_locale'
lib/middleware/omniauth_bypass_middleware.rb:71:in `call'
lib/content_security_policy/middleware.rb:12:in `call'
lib/middleware/anonymous_cache.rb:368:in `call'
config/initializers/100-quiet_logger.rb:23:in `call'
config/initializers/100-silence_logger.rb:31:in `call'
lib/middleware/enforce_hostname.rb:23:in `call'
lib/middleware/request_tracker.rb:202:in `call'
```

thanks

**Comment by merefield** [comment]
Thanks for the report, PR incoming, apologies (btw, the backtrace required is a little longer, but no bother we've had another report).

**Comment by merefield** [comment]
PR merged, could you please update and let me know if it resolves your issue?

**Comment by juandans01** [comment]
Hey, just updated and it's working again
thank you so much!
